name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./앱/pom.xml
          mvn clean package -f ./가게/pom.xml
          mvn clean package -f ./결제/pom.xml
          mvn clean package -f ./배달/pom.xml
          mvn clean package -f ./BoundedContext1216/pom.xml

      - name: Docker Build and push for 앱
        uses: docker/build-push-action@v4
        with:
          context: ./앱
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/앱:latest
            ghcr.io/${{ github.repository }}/앱:${{ github.ref_name }}
            
      - name: Docker Build and push for 가게
        uses: docker/build-push-action@v4
        with:
          context: ./가게
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/가게:latest
            ghcr.io/${{ github.repository }}/가게:${{ github.ref_name }}
            
      - name: Docker Build and push for 결제
        uses: docker/build-push-action@v4
        with:
          context: ./결제
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/결제:latest
            ghcr.io/${{ github.repository }}/결제:${{ github.ref_name }}
            
      - name: Docker Build and push for 배달
        uses: docker/build-push-action@v4
        with:
          context: ./배달
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/배달:latest
            ghcr.io/${{ github.repository }}/배달:${{ github.ref_name }}
            
      - name: Docker Build and push for BoundedContext1216
        uses: docker/build-push-action@v4
        with:
          context: ./BoundedContext1216
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/boundedcontext1216:latest
            ghcr.io/${{ github.repository }}/boundedcontext1216:${{ github.ref_name }}
            
