apiVersion: apps/v1
kind: Deployment
metadata:
  name: 가게
  labels:
    app: 가게
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 가게
  template:
    metadata:
      labels:
        app: 가게
    spec:
      containers:
        - name: 가게
          image: "username/가게:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
